---

# 'invgroup' here is a hash
- name: checks for group {{invgroup.key }}
  template: src=".{{ config_dir }}/{{ invgroup.key }}_template.j2"
            dest="{{ config_dir }}/{{ item }}_{{ invgroup.key }}.cfg"
  with_items: "{{ invgroup.value }}"

# boom, got it. NB: bear in mind each host
# can be in multiple groups, so you might want
# to generate templates based on hostname+group
