---

- name: create config directory
  file: path={{ config_dir }} state=directory

- name: generate checks for {{ item }}
  template: src=host-template.cfg.j2
            dest={{ config_dir }}/{{ item }}.cfg
  with_items:
    - "{{ groups.all }}"

